import { NextRequest, NextResponse } from "next/server"
import { Client } from "@notionhq/client"

// Simple Markdown to Notion Block Parser
function parseMarkdownToRichText(text: string): any[] {
  const result: any[] = []
  // Matches bold **text**, links [text](url), and plain text
  const regex = /(\*\*.*?\*\*|\[.*?\]\(.*?\))/g
  let lastIndex = 0
  let match

  while ((match = regex.exec(text)) !== null) {
    // Add text before the match
    if (match.index > lastIndex) {
      result.push({
        type: "text",
        text: { content: text.substring(lastIndex, match.index) }
      })
    }

    const part = match[0]
    if (part.startsWith("**") && part.endsWith("**")) {
      // Bold
      result.push({
        type: "text",
        text: { content: part.slice(2, -2) },
        annotations: { bold: true }
      })
    } else if (part.startsWith("[")) {
      // Link
      const linkMatch = part.match(/\[(.*?)\]\((.*?)\)/)
      if (linkMatch) {
        result.push({
          type: "text",
          text: { content: linkMatch[1], link: { url: linkMatch[2] } }
        })
      }
    }

    lastIndex = regex.lastIndex
  }

  // Add remaining text
  if (lastIndex < text.length) {
    result.push({
      type: "text",
      text: { content: text.substring(lastIndex) }
    })
  }

  return result.length > 0 ? result : [{ type: "text", text: { content: text } }]
}

export async function POST(req: NextRequest) {
  try {
    const { idea, stack, output } = await req.json()
    
    const notionToken = (process.env.NOTION_TOKEN || "").trim()
    const parentPageId = (process.env.NOTION_PARENT_PAGE_ID || "").trim()

    if (!notionToken || !parentPageId) {
      return NextResponse.json(
        { error: "Notion configuration missing (NOTION_TOKEN or NOTION_PARENT_PAGE_ID)" },
        { status: 500 }
      )
    }

    const notion = new Client({ auth: notionToken })

    // 1. Define systematic blocks
    const blocks: any[] = [
      {
        object: "block",
        type: "callout",
        callout: {
          rich_text: [
            { 
              type: "text", 
              text: { content: "SYSTEMATIC PROJECT BLUEPRINT" }, 
              annotations: { bold: true, color: "blue" } 
            },
            { type: "text", text: { content: "\nGenerated by StackFind AI — Your architect for the Indian Tech Stack." } }
          ],
          icon: { external: { url: "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/zap.png" } },
          color: "blue_background"
        }
      },
      {
        object: "block",
        type: "heading_1",
        heading_1: {
          rich_text: [{ type: "text", text: { content: "Project Vision" } }]
        }
      },
      {
        object: "block",
        type: "quote",
        quote: {
          rich_text: [{ type: "text", text: { content: idea || "Custom architecture selection" }, annotations: { italic: true } }]
        }
      },
      {
        object: "block",
        type: "divider",
        divider: {}
      },
      {
        object: "block",
        type: "heading_1",
        heading_1: {
          rich_text: [{ type: "text", text: { content: "Selected Architecture" } }]
        }
      },
      {
        object: "block",
        type: "table",
        table: {
          table_width: 3,
          has_column_header: true,
          children: [
            {
              type: "table_row",
              table_row: {
                cells: [
                  [{ type: "text", text: { content: "Service/Tool", annotations: { bold: true } } }],
                  [{ type: "text", text: { content: "Category", annotations: { bold: true } } }],
                  [{ type: "text", text: { content: "Budget Estimate", annotations: { bold: true } } }]
                ]
              }
            },
            ...stack.map((t: any) => ({
              type: "table_row",
              table_row: {
                cells: [
                  [{ type: "text", text: { content: t.name, annotations: { bold: true } } }],
                  [{ type: "text", text: { content: t.categories?.[0] || "Tool" } }],
                  [{ type: "text", text: { content: t.startingPriceInr ? `₹${t.startingPriceInr}/mo` : (t.startingPriceUsd ? `$${t.startingPriceUsd}/mo` : "Free") } }]
                ]
              }
            }))
          ]
        }
      },
      {
        object: "block",
        type: "heading_1",
        heading_1: {
          rich_text: [{ type: "text", text: { content: "Execution Strategy" } }]
        }
      }
    ]

    // 2. Parse Markdown Output to Notion Blocks
    const lines = output.split("\n")
    for (const line of lines) {
      const trimmed = line.trim()
      if (!trimmed && blocks[blocks.length - 1]?.type !== "divider") continue

      if (trimmed.startsWith("## ")) {
        blocks.push({
          object: "block",
          type: "heading_2",
          heading_2: { rich_text: parseMarkdownToRichText(trimmed.replace("## ", "")) }
        })
      } else if (trimmed.startsWith("### ")) {
        blocks.push({
          object: "block",
          type: "heading_3",
          heading_3: { rich_text: parseMarkdownToRichText(trimmed.replace("### ", "")) }
        })
      } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
        blocks.push({
          object: "block",
          type: "bulleted_list_item",
          bulleted_list_item: { rich_text: parseMarkdownToRichText(trimmed.substring(2)) }
        })
      } else if (/^\d+\. /.test(trimmed)) {
        blocks.push({
          object: "block",
          type: "numbered_list_item",
          numbered_list_item: { rich_text: parseMarkdownToRichText(trimmed.replace(/^\d+\. /, "")) }
        })
      } else if (trimmed) {
        blocks.push({
          object: "block",
          type: "paragraph",
          paragraph: { rich_text: parseMarkdownToRichText(trimmed) }
        })
      }
    }

    // 3. Add Project Workflow & Next Steps (Systematic Checklist)
    blocks.push(
      { object: "block", type: "divider", divider: {} },
      {
        object: "block",
        type: "heading_1",
        heading_1: {
          rich_text: [{ type: "text", text: { content: "Founder's Workflow" } }]
        }
      },
      {
        object: "block",
        type: "to_do",
        to_do: { rich_text: [{ type: "text", text: { content: "Register domains & Social handles" } }], checked: false }
      },
      {
        object: "block",
        type: "to_do",
        to_do: { rich_text: [{ type: "text", text: { content: "Set up development environments for the selected stack" } }], checked: false }
      },
      {
        object: "block",
        type: "to_do",
        to_do: { rich_text: [{ type: "text", text: { content: "Initialize Git repository & CI/CD pipeline" } }], checked: false }
      },
      {
        object: "block",
        type: "to_do",
        to_do: { rich_text: [{ type: "text", text: { content: "Integrate Authentication & Database schema" } }], checked: false }
      },
      {
        object: "block",
        type: "to_do",
        to_do: { rich_text: [{ type: "text", text: { content: "Design landing page & core UI components" } }], checked: false }
      },
      {
        object: "block",
        type: "to_do",
        to_do: { rich_text: [{ type: "text", text: { content: "Apply for Managed Billing via StackFind" } }], checked: true }
      },
      {
        object: "block",
        type: "to_do",
        to_do: { rich_text: [{ type: "text", text: { content: "Launch MVP & Collect User Feedback" } }], checked: false }
      },
      { object: "block", type: "divider", divider: {} },
      {
        object: "block",
        type: "callout",
        callout: {
          rich_text: [
            { type: "text", text: { content: "Ready to build? " } },
            { 
              type: "text", 
              text: { content: "Return to StackFind", link: { url: "https://stackfind.in/playground" } },
              annotations: { bold: true, color: "blue" }
            },
            { type: "text", text: { content: " to refine your stack or request managed billing." } }
          ],
          icon: { emoji: "⚡" },
          color: "gray_background"
        }
      }
    )

    console.log("Notion: Creating page with", blocks.length, "blocks")

    const response = await notion.pages.create({
      parent: { page_id: parentPageId },
      icon: { external: { url: "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/zap.png" } },
      cover: {
        type: "external",
        external: { url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80" }
      },
      properties: {
        title: {
          title: [
            {
              text: {
                content: `🚀 Blueprint: ${idea.substring(0, 50)}${idea.length > 50 ? "..." : ""}`
              }
            }
          ]
        }
      },
      children: blocks.slice(0, 100)
    })

    console.log("Notion: Page created successfully:", (response as any).url)
    return NextResponse.json({ success: true, url: (response as any).url })
  } catch (error: any) {
    console.error("Notion Export API Error:", error)
    // Return specific error to client
    const errorMessage = error.message || "Unknown Notion error"
    const statusCode = error.status || 500
    return NextResponse.json({ 
      error: `Notion Error: ${errorMessage}. Please ensure the 'StackFind' integration is shared with your parent page.`,
      details: error.code || null
    }, { status: statusCode })
  }
}
